command:
  - "uvicorn"
  - "app:app"
  - "--host"
  - "0.0.0.0"
  - "--port"
  - "8000"

env:
  - name: SERVING_ENDPOINT_NAME
    value: ""  # e.g. "databricks-meta-llama-3-3-70b-instruct"

  - name: LAKEBASE_INSTANCE_NAME
    value: ""  # e.g. "trex-game-db"

  - name: LAKEBASE_HOST
    value: ""  # DNS da instância Lakebase (read_write_dns)

  - name: LAKEBASE_DATABASE
    value: "databricks_postgres"

  - name: LAKEBASE_PORT
    value: "5432"

  - name: GENIE_SPACE_ID
    value: ""  # ID do Genie Space (criado no Passo 9)
