command:
  - "uvicorn"
  - "app:app"
  - "--host"
  - "0.0.0.0"
  - "--port"
  - "8000"

env:
  - name: SERVING_ENDPOINT_NAME
    value: "databricks-meta-llama-3-3-70b-instruct"

  - name: LAKEBASE_INSTANCE_NAME
    value: "trex-game-db"

  - name: LAKEBASE_HOST
    value: "instance-8d7f6ced-85e6-4c05-af9d-068669d2a42d.database.azuredatabricks.net"

  - name: LAKEBASE_DATABASE
    value: "databricks_postgres"

  - name: LAKEBASE_PORT
    value: "5432"

  - name: GENIE_SPACE_ID
    value: "01f10e93a00012ba90fa5af86758879e"
